# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: true
    - name: Install and Build
      run: yarn && yarn run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        # ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: ./dist
    #- name: Build
    #  uses: JamesIves/github-pages-deploy-action@master
    #env:
    #    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #    BRANCH: gh-pages
    #    FOLDER: build
    #    BUILD_SCRIPT: yarn && yarn run build
        #- run: yarn  # 相当于npm install
        #- run: yarn run build --if-present
    # - run: npm test
